# Generated by Django 4.2 on 2024-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'Essencial'), ('2', 'Superfluo'), ('3', 'Divida ou Investimento')], default='1', max_length=1, verbose_name='tipo'),
        ),
    ]
