# Generated by Django 4.2 on 2024-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='method',
            field=models.CharField(choices=[('1', 'Essencial'), ('2', 'Superfluo'), ('3', 'Divida ou Investimento')], default='1', max_length=1, verbose_name='método 50-30-20'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'Fixa'), ('2', 'Variavel')], default='1', max_length=1, verbose_name='tipo'),
        ),
    ]
