# Generated by Django 4.2 on 2024-07-30 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CC', 'Conta Corrente'), ('DN', 'Dinheiro'), ('CT', 'Cartão Crédito'), ('IN', 'Investimentos')], default='CC', max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('opening_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Investimento'), ('4', 'Transferencia')], default='1', max_length=1)),
                ('essential', models.BooleanField(default=True)),
                ('planned_value', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=datetime.datetime.now)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], default='D', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-due_date', 'payment_date', 'type'],
            },
        ),
    ]
