# Generated by Django 4.2 on 2024-07-31 20:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='essential',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.BooleanField(choices=[('1', 'Essencial'), ('2', 'Superfluo'), ('3', 'Divida ou Investimento')], default='1', max_length=1, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='data transação'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='saldo atual'),
        ),
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='logotipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='saldo inicial'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('DN', 'Dinheiro'), ('CT', 'Cartão Crédito'), ('IN', 'Investimentos')], default='CC', max_length=2, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Investimento'), ('4', 'Transferencia')], default='1', max_length=1, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='planned_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='valor planejamento'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='finance.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='data vencimento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='data pagamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], default='D', max_length=1, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
