# Generated by Django 4.2 on 2024-07-31 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_category_options_remove_category_essential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='data vencimento'),
        ),
    ]
