# Generated by Django 4.2 on 2024-07-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', 'due_date', 'payment_date', 'type'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
