# Generated by Django 4.2 on 2024-08-14 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('DN', 'Dinheiro'), ('CT', 'Cartão Crédito'), ('IN', 'Investimentos')], default='CC', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Investimento'), ('4', 'Transferencia')], default='1', max_length=1, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='method',
            field=models.CharField(choices=[('1', 'Essencial'), ('2', 'Superfluo'), ('3', 'Divida ou Investimento')], default='1', max_length=1, verbose_name='Método 50-30-20'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='planned_value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Valor Planejado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'Fixa'), ('2', 'Variavel')], default='1', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data da Transação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], default='D', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
