# Generated by Django 4.2 on 2024-09-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='method',
        ),
    ]
