# Generated by Django 4.2 on 2024-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_category_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'Renda'), ('2', 'Despesa Fixa'), ('3', 'Despesa Variável Essencial'), ('4', 'Despesa Variável Supérflua'), ('5', 'Despesa Variável Eventual'), ('6', 'Outros')], default='1', max_length=1, verbose_name='Tipo'),
        ),
    ]
