# Generated by Django 4.2 on 2024-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_account_active_category_active_transaction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(default='sem_imagem.png', upload_to='images/', verbose_name='Logotipo'),
        ),
    ]
