# Generated by Django 4.2 on 2024-10-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_account_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'Renda'), ('2', 'Despesa Fixa'), ('3', 'Despesa Variável Essencial'), ('4', 'Despesa Variável Supérflua'), ('5', 'Despesa Variável Eventual'), ('6', 'Investimento'), ('7', 'Divida')], default='1', max_length=1, verbose_name='Tipo'),
        ),
    ]
