# Generated by Django 4.2 on 2024-10-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_nature',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='fixa', max_length=15, verbose_name='Natureza da Categoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_priority',
            field=models.CharField(choices=[('essencial', 'Essencial'), ('superflua', 'Superflua'), ('div_invest', 'Dívida Investimento')], default='essencial', max_length=15, verbose_name='Prioridade(Método 50/30/20)'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('investimento', 'Investimento'), ('transferencia', 'Transferência')], default='despesa', max_length=15, verbose_name='Tipo de Categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category', verbose_name='Categoria Pai'),
        ),
    ]
