# Generated by Django 4.2 on 2024-10-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_category_options_remove_category_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_priority',
            field=models.CharField(choices=[('essencial', 'Essencial'), ('superflua', 'Superflua'), ('reserva', 'Reserva')], default='essencial', max_length=15, verbose_name='Prioridade(Método 50/30/20)'),
        ),
    ]
