# Generated by Django 4.2 on 2024-10-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_category_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Ordem de Apresentação'),
            preserve_default=False,
        ),
    ]
