# Generated by Django 4.2 on 2024-10-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(verbose_name='Ordem de Apresentação'),
        ),
    ]
