# Generated by Django 4.2 on 2024-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_priority',
            field=models.CharField(choices=[('essencial', 'Essencial(50%)'), ('superflua', 'Superflua(30%)'), ('reserva', 'Reserva(20%)')], default='essencial', max_length=15, verbose_name='Prioridade(Método 50/30/20)'),
        ),
    ]
