# Generated by Django 4.2 on 2025-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_category_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago ou Recebido'),
        ),
    ]
